# Site settings
title: Arc Sessions
email: ben@arcpublications.co.uk
description: > # this means to ignore newlines
  A new site for live poetry.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sessions.arctour.co.uk" # the base hostname & protocol for your site
twitter_username: Arc_Poetry
# github_username:  jekyll

# Build settings
exclude: ["node_modules","package.json","Gruntfile.js"]
sass:
  style: compressed
