title: Arc Sessions
email: ben@arcpublications.co.uk
description: A new site for live poetry.
baseurl: "/sessions" # the subpath of your site, e.g. /blog/
url: "https://arcpublications.co.uk"
twitter_username: Arc_Poetry

exclude:
  - node_modules
  - package.json
  - src
  - webpack.config.js
  - yarn-error.log
  - yarn.lock

sass:
  style: compressed
